### ISSUE TITLE
[Internal Build] - Server listen() method throws IOException: Stream Closed

### ISSUE THREAD

**Issue by ANDERSONTECHWERKS** [ANDERSONTECHWERKS/Transponder#10]
This is likely caused by a premature closure in the tClient class. Look through tClient's run() method and see if we can't find where the socket is being closed in tClient.

tClient-side 
```
---TransponderTCP---

Choose Transponder Mode: 

1 - Server
2 - Client

2
Client IP Address: 

127.0.0.1
Client Socket:

7000
Remote Server IP Address:

127.0.0.1
Remote Server Socket:

6969
Debug mode? 

1 - ON
2 - OFF
1
---COMMANDS---
1. Transponder Status
2. Configure Transponder
3. Start Transponder
4. Stop Transponder
5. Exit
3
Transponder starting!
Thread information:
 Thread state: RUNNABLE
---COMMANDS---
1. Transponder Status
2. Configure Transponder
3. Start Transponder
4. Stop Transponder
5. Exit
debugObj not set for client /127.0.0.1:6969
Not using debugObj for debug purposes! Messages only!
tClient| clientSocketLocal local address: /127.0.0.1 Port: 7000

tClient| clientSocketLocal remote address: /127.0.0.1:6969 Port: 6969

tClient| Payload recieved! Payload toString() reads: 

- - - - - - - - - -
Message#: 6
Message Name: FAT

- - - - - - - - - -
Payload recieved at time 1627667733275

Message#: 6
Message Name: FAT
```

tServer-side:
```
java.io.IOException: Stream closed
	at java.base/java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:176)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:220)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
	at java.base/java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2832)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:3159)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3169)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1630)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:493)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:451)
	at transponderTCP.tServerTCP.listen(tServerTCP.java:92)
	at transponderTCP.tServerTCP.run(tServerTCP.java:422)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by ANDERSONTECHWERKS** [comment]
Fixed in 47802e6f2807ea0f7b5be3828d428b4bc1805139
