### ISSUE TITLE
java.net.SocketException: Connection reset by peer

### ISSUE THREAD

**Issue by ANDERSONTECHWERKS** [ANDERSONTECHWERKS/Transponder#3]
When stepping through my test cases, sending a single payload, I find that there is no issue transmitting a Payload Object from the Server to the Client.

However, when trying to "Run" in Eclipse normally: I get the following error.

```
tServer| ServerSocket and Stream Status:
java.io.ObjectOutputStream@50fa4de1
java.net.Socket$SocketOutputStream@5e3db98e
Socket[**_REDACTED INFORMATION]_**
tServer| Socket Exception occurred!
Setting stopFlag to TRUE!
java.net.SocketException: Connection reset by peer
	at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:421)
	at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:441)
	at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:825)
	at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1007)
	at java.base/java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1883)
	at java.base/java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1792)
	at java.base/java.io.ObjectOutputStream.writeNonProxyDesc(ObjectOutputStream.java:1287)
	at java.base/java.io.ObjectOutputStream.writeClassDesc(ObjectOutputStream.java:1232)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1428)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)
	at java.base/java.io.ObjectOutputStream.writeFatalException(ObjectOutputStream.java:1583)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:352)
	at transponderTCP.tServer.transmitPayload(tServer.java:153)
	at transponderTCP.tServer.run(tServer.java:181)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

Currently writing more *secretTests* to try to figure this out. Might need to investigate Socket behavior more thoroughly.

**Comment by ANDERSONTECHWERKS** [comment]
Believe this issue is resolved
